receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s
    send_batch_max_size: 1000
    send_batch_size: 100

exporters:
  datadog:
    retry_on_failure:
      enabled: true
    api:
      site: 'datadoghq.com'
      key: ''
    metrics:
      sums:
        cumulative_monotonic_mode: raw_value
      histograms:
        mode: distributions
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200


service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors:  [batch]
      exporters: [datadog]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog]